- name: Install APT packages that allow HTTPS connections
  apt:
    name: apt-transport-https 
    
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: "hkps://keys.openpgp.org"
    id: "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"

- name: add a key used to sign RabbitMQ
  apt_key:
    url: "{{item}}"
  with_items:
    - https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key
    - https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key

- name: add the apt repository
  apt_repository:
    repo: "{{item}}"
    state: present
    filename: rabbitmq
  with_items:
    - deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ansible_distribution_release}} main
    - deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ansible_distribution_release}} main
    - deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ansible_distribution_release}} main
    - deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ansible_distribution_release}} main 

- name: Copy Erlang and RabbitMQ pinn file
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - {src: "erlang",dest: "/etc/apt/preferences.d/erlang"}
    - {src: "rabbitmq",dest: "/etc/apt/preferences.d/rabbitmq"}

- name: Install RabbitMQ and Erlang
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - "erlang=1:{{rabbitmq_erlang_major_version}}.*"
    - "rabbitmq-server={{rabbitmq_version}}.*"
