- name: Install APT packages that allow HTTPS connections
  apt:
    name: apt-transport-https 

- name: add key for RabbitMQ Erlang
  shell: |
    apt-key adv --keyserver "keyserver.ubuntu.com" --recv-keys "F77F1EDA57EBB1CC"
    apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"

- name: add a key used to sign RabbitMQ
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

- name: add the apt repository
  apt_repository:
    repo: "{{item}}"
    state: present
    filename: rabbitmq
  with_items:
    - deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ansible_distribution_release}} main
    - deb-src http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ansible_distribution_release}} main
    - deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ansible_distribution_release}} main
    - deb-src https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ansible_distribution_release}} main

- name: Install RabbitMQ and Erlang
  apt:
    name: "{{item}}"
  with_items:
    - "erlang=1:{{rabbitmq_erlang_major_version}}.*"
    - "rabbitmq-server={{rabbitmq_version}}.*"

- name: Copy Erlang and RabbitMQ version pinning file
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - {src: "erlang_pinn",dest: "/etc/apt/preferences.d/erlang"}
    - {src: "rabbitmq_pinn",dest: "/etc/apt/preferences.d/rabbitmq"}
    